
#version 460
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_EXT_maximal_reconvergence : enable

#pragma scheduler(HSA)

layout(set = 0, binding = 0) volatile buffer TEST {
	uint x;
} test; 


layout(local_size_x = 2, local_size_y = 1, local_size_z = 1) in;
layout(tla_subgroup_size = 2) in;
layout(tla_num_workgroups = 1) in;

void main()
{
    uint read = 0;
    uint gid_x = gl_GlobalInvocationID.x;
    uint index = (gid_x + 1) % 2; // ensure gid_x is either 0 or 1
	atomicOr(test.x, 1 << index); // set bit at position gid_x
    if (gid_x == 0) {
        // scope: invocation, storage: buffer, memory semantics: relax
        subgroupAll(false); // this really does nothing but acts like a subgroup synchronization
	    // for memory semantics spec, see: https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Memory_Semantics_-id-
        read = test.x;
    } else {
        // subgroupAll(false);
        read = test.x;
    }
    subgroupBarrier();
    assert( (read >> gid_x) != 0);
}

