
#version 460
#pragma scheduler(OBE)
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_basic : enable

layout(set = 0, binding = 3) volatile buffer PICKTHREAD {
	uint pick_thread;
} pickthread;

layout(set = 0, binding = 0) volatile buffer TEST {
	uint x;
} test; 

layout(local_size_x = 2) in;
layout(tla_subgroup_size = 2) in;
layout(tla_num_workgroups = 2) in;

void main()
{
	 uint subgroup_size = gl_SubgroupSize;
	 uint subgroup_id = gl_SubgroupID;
	 uint workgroup_id = gl_WorkGroupID.x;
	uint gid_x = gl_GlobalInvocationID.x;
	uint pc = 0u;
	uint round_robin = 0u;

	if (workgroup_id == 0 && subgroup_id == 0) { 
	   int terminate = 0;

	while (true) {
	   if (subgroupAny(terminate == 1)) {
	   break;
	}
	pickthread.pick_thread = uint(round_robin % subgroup_size);
	if (pickthread.pick_thread == gl_SubgroupInvocationID) {
	  switch(pc) {

	  case 0: 
		if (atomicExchange(test.x, 0) == 1) { 
		   pc = 0u;
		}
		else {
		   pc = pc + 1u;
		}
		break;

	  case 1:
		terminate = 1;
		break;

	     }
	   }
	   round_robin += 1u;
	   pc = subgroupBroadcast(pc, pickthread.pick_thread);
	}
	}

	if (workgroup_id == 1 && subgroup_id == 0) { 
	   int terminate = 0;

	while (true) {
	   if (subgroupAny(terminate == 1)) {
	   break;
	}
	pickthread.pick_thread = uint(round_robin % subgroup_size);
	if (pickthread.pick_thread == gl_SubgroupInvocationID) {
	  switch(pc) {

	  case 0: 
		if (atomicExchange(test.x, 1) == 0) { 
		   pc = 0u;
		}
		else {
		   pc = pc + 1u;
		}
		break;

	  case 1:
		terminate = 1;
		break;

	     }
	   }
	   round_robin += 1u;
	   pc = subgroupBroadcast(pc, pickthread.pick_thread);
	}
	}
}